### ISSUE TITLE
How to generate an empty object for workflow_dispatch?

### ISSUE THREAD

**Issue by armanm** [optimumBA/github_workflows_generator#2]
I'm trying to generate a workflow which supports manual triggers using `workflow_dispatch`. For that to happen we need to generate this `yml` content where `workflow_dispatch` is an empty object.

```yml
on:
  workflow_dispatch:
```

However this does not seem possible using this package. Both of these variants can not actually produce what is needed for GH linter to be happy.

```elixir
on: [
  workflow_dispatch: []
]
```
```elixir
on: [
  workflow_dispatch: %{}
]
```

**Comment by almirsarajcic** [comment]
Yeah, I have a similar issue where I need
```yaml
on:
  pull_request:
```
and, similar to your solution, mine was:
```yaml
on:
  pull_request: []
```
(YAML)
```elixir
on: [
  pull_request: []
]
```
(Elixir)

Honestly, I don't know how to make the linter happy. Maybe, we can check whether the list is empty, and if it is, then remove it.

**Comment by almirsarajcic** [comment]
@armanm, can you try again with
```elixir
{:github_workflows_generator, github: "optimumBA/github_workflows_generator", branch: "remove_fast_yaml", only: :dev, runtime: false},
```
